# Generated by Django 2.1.15 on 2020-06-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
