# Generated by Django 2.1.15 on 2020-06-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.CharField(default='default_username', max_length=200),
        ),
    ]
