# Generated by Django 2.1.15 on 2020-06-13 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.CharField(max_length=20)),
                ('deathday', models.CharField(max_length=20, null=True)),
                ('gender', models.IntegerField()),
                ('profile_path', models.CharField(max_length=200, null=True)),
                ('popularity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ActorLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Actor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='like_users',
            field=models.ManyToManyField(related_name='like_actors', through='actors.ActorLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
