# Generated by Django 2.1.15 on 2020-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='popularity',
            field=models.FloatField(null=True),
        ),
    ]
