# Generated by Django 2.1.15 on 2020-06-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='popularity',
            field=models.FloatField(),
        ),
    ]
