# Generated by Django 2.1.15 on 2020-06-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20200613_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='deathday',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
