# Generated by Django 2.1.15 on 2020-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20200613_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
