# Generated by Django 2.1.15 on 2020-06-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200613_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_name',
        ),
        migrations.AddField(
            model_name='genre',
            name='en_genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='genre',
            name='kr_genre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
