# Generated by Django 2.1.15 on 2020-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200614_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
